version: '3.8'

services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - ../content:/app/content/
      - ./downloads:/app/downloads
    ports:
      - 8000:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
