version: '3.8'

services:
  BACKEND:
    build: .
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ../content:/app/content/
    PORT:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
