version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
