version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./downloads:/app/downloads
    networks:
      - app-network

  celery_worker:
    build: .
    env_file:
      - .env
    command: celery -A telegram_file_bot.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./downloads:/app/downloads
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
